// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ip-info": {
            "post": {
                "description": "return country information and currency rate to UAH",
                "produces": [
                    "application/json"
                ],
                "summary": "get ip info",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ipinfo.requestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ipinfo.responseBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorops.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "currencies.CurrencyRateToUAH": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "rateToUAH": {
                    "type": "number"
                }
            }
        },
        "errorops.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "value": {}
            }
        },
        "ipinfo.requestBody": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "ipinfo.responseBody": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "currencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/currencies.CurrencyRateToUAH"
                    }
                },
                "currentTime": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "IPCurrency",
	Description:      "API for IPCurrency Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
